# -*- coding: utf-8 -*-
"""RR_GBM_RF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Cxb8GVthzBwO1hiR_5UewIzL9dLKEA5

## Plot ridge regression learning curve data
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the CSV file
df_learning_curve = pd.read_csv('/content/drive/MyDrive/Coursework/CHEMENG 277/Final Project/ridge_learning_curve.csv')

# Filter out the data point where n_train is 104
df_learning_curve_filtered = df_learning_curve[df_learning_curve['n_train'] != 104].copy()

# Display the first 5 rows of the filtered DataFrame
display(df_learning_curve_filtered.head())

# Now, let's create bar plots for MAE and RMSE with the filtered data.

fig, axes = plt.subplots(1, 2, figsize=(16, 6)) # Increased figure width for better display

# Bar plot for MAE
sns.barplot(x='n_train', y='MAE_mean', data=df_learning_curve_filtered, ax=axes[0], palette='viridis')
axes[0].set_title('Mean Absolute Error (MAE) for Ridge Regression', fontsize=14)
axes[0].set_xlabel('Number of Training Data Points (n_train)', fontsize=12)
axes[0].set_ylabel('MAE', fontsize=12)
axes[0].tick_params(axis='x', rotation=0, labelsize=10)
axes[0].tick_params(axis='y', labelsize=10)

# Bar plot for RMSE
sns.barplot(x='n_train', y='RMSE_mean', data=df_learning_curve_filtered, ax=axes[1], palette='magma')
axes[1].set_title('Root Mean Squared Error (RMSE) for Ridge Regression', fontsize=14)
axes[1].set_xlabel('Number of Training Data Points (n_train)', fontsize=12)
axes[1].set_ylabel('RMSE', fontsize=12)
axes[1].tick_params(axis='x', rotation=0, labelsize=10)
axes[1].tick_params(axis='y', labelsize=10)

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the oof_predictions_ridge.csv file
df_predictions = pd.read_csv('/content/drive/MyDrive/Coursework/CHEMENG 277/Final Project/oof_predictions_ridge.csv')

# Display the first 5 rows to understand the structure and column names
display(df_predictions.head())

"""## Plotting of various metrics from ridge regression on initial data set."""

# Using the correct column names from the df_predictions DataFrame
true_col = 'deadFraction'
pred_col = 'deadFraction_pred_oof'

# Calculate residuals
df_predictions['residuals'] = df_predictions[true_col] - df_predictions[pred_col]

fig, axes = plt.subplots(1, 2, figsize=(18, 7))

# Scatter plot of Predicted vs True Values
sns.scatterplot(x=true_col, y=pred_col, data=df_predictions, ax=axes[0])
axes[0].plot([df_predictions[true_col].min(), df_predictions[true_col].max()],
             [df_predictions[true_col].min(), df_predictions[true_col].max()],
             '--r', label='Perfect Prediction')
axes[0].set_title('Predicted vs. True Values', fontsize=16)
axes[0].set_xlabel('True Values', fontsize=12)
axes[0].set_ylabel('Predicted Values', fontsize=12)
axes[0].legend()
axes[0].grid(True, linestyle='--', alpha=0.7)

# Residual Plot (Residuals vs. Predicted Values)
sns.scatterplot(x=pred_col, y='residuals', data=df_predictions, ax=axes[1])
axes[1].axhline(y=0, color='r', linestyle='--')
axes[1].set_title('Residuals vs. Predicted Values', fontsize=16)
axes[1].set_xlabel('Predicted Values', fontsize=12)
axes[1].set_ylabel('Residuals', fontsize=12)
axes[1].grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ---- load ----
# Upload oof_predictions_ridge.csv to Colab (Files panel) or mount Drive and set the path.
csv_path = "/content/drive/MyDrive/Coursework/CHEMENG 277/Final Project/oof_predictions_ridge.csv"
df = pd.read_csv(csv_path)

# Basic sanity
assert "deadFraction" in df.columns
assert "deadFraction_pred_oof" in df.columns
df["residual_oof"] = df["deadFraction_pred_oof"] - df["deadFraction"]

# Color map for placement
cmap = {"T":"tab:blue", "S":"tab:orange", "SZ":"tab:green", "TS":"tab:red"}
# Correcting the list comprehension to use the actual placement codes from the DataFrame
placements = [p for p in ["T","S","SZ","TS"] if p in df["placement"].unique()]

# Helper for diagonal limits
def diag_limits(a, b, pad_frac=0.03):
    lo = min(np.min(a), np.min(b))
    hi = max(np.max(a), np.max(b))
    pad = pad_frac*(hi-lo if hi>lo else 1.0)
    return lo-pad, hi+pad

# ---- 1) Predicted vs true ----
plt.figure(figsize=(6,6), dpi=140)
for p in placements:
    m = (df["placement"] == p)
    plt.scatter(df.loc[m,"deadFraction"], df.loc[m,"deadFraction_pred_oof"],
                s=22, alpha=0.8, color=cmap.get(p,None), label=p)
lo, hi = diag_limits(df["deadFraction"], df["deadFraction_pred_oof"])
plt.plot([lo,hi],[lo,hi],"k--",lw=1)
plt.xlim(lo,hi); plt.ylim(lo,hi)
plt.xlabel("True dead volume fraction")
plt.ylabel("OOF predicted dead volume fraction")
plt.title("Ridge: predicted vs true")
plt.legend(title="placement")
plt.grid(alpha=0.25)
plt.tight_layout()
plt.show()

# ---- 2) Residual vs Qtot ----
if "Qtot_uLmin" in df.columns:
    plt.figure(figsize=(6.5,4.5), dpi=140)
    for p in placements:
        m = (df["placement"] == p)
        plt.scatter(df.loc[m,"Qtot_uLmin"], df.loc[m,"residual_oof"],
                    s=22, alpha=0.8, color=cmap.get(p,None), label=p)
    plt.axhline(0, color="k", lw=1, ls="--")
    plt.xlabel("Qtot (uL/min)")
    plt.ylabel("Residual (pred - true)")
    plt.title("Residual vs Qtot")
    plt.legend(title="placement")
    plt.grid(alpha=0.25)
    plt.tight_layout()
    plt.show()

# ---- 3) Residual vs N ----
if "N" in df.columns:
    plt.figure(figsize=(6.5,4.5), dpi=140)
    for p in placements:
        m = (df["placement"] == p)
        plt.scatter(df.loc[m,"N"], df.loc[m,"residual_oof"],
                    s=22, alpha=0.8, color=cmap.get(p,None), label=p)
    plt.axhline(0, color="k", lw=1, ls="--")
    plt.xlabel("N injectors")
    plt.ylabel("Residual (pred - true)")
    plt.title("Residual vs N")
    plt.legend(title="placement")
    plt.grid(alpha=0.25)
    plt.tight_layout()
    plt.show()

# ---- 4) Residual boxplot by placement ----
plt.figure(figsize=(6,4.5), dpi=140)
data = [df.loc[df["placement"]==p, "residual_oof"].values for p in placements]
plt.boxplot(data, labels=placements, showfliers=True)
plt.axhline(0, color="k", lw=1, ls="--")
plt.xlabel("placement")
plt.ylabel("Residual (pred - true)")
plt.title("Residual distribution by placement")
plt.grid(axis="y", alpha=0.25)
plt.tight_layout()
plt.show()

# ---- 5) Optional: residual vs geometry (if present) ----
if "pipeHeight_mm" in df.columns and "D" in df.columns:
    # Simple scatter colored by placement; you can facet later if desired
    plt.figure(figsize=(6.5,4.5), dpi=140)
    for p in placements:
        m = (df["placement"] == p)
        plt.scatter(df.loc[m,"pipeHeight_mm"], df.loc[m,"residual_oof"],
                    s=22, alpha=0.8, color=cmap.get(p,None), label=p)
    plt.axhline(0, color="k", lw=1, ls="--")
    plt.xlabel("pipeHeight_mm")
    plt.ylabel("Residual (pred - true)")
    plt.title("Residual vs pipeHeight")
    plt.legend(title="placement")
    plt.grid(alpha=0.25)
    plt.tight_layout()
    plt.show()

"""Plotting to generate heat map of points identified by uncertainty-based sampling."""

#!/usr/bin/env python3
import argparse
import pandas as pd
import numpy as np

try:
    import matplotlib
    # matplotlib.use("Agg") # Commented out: 'Agg' backend prevents plots from showing in Colab output
    import matplotlib.pyplot as plt
except ImportError:
    raise ImportError("matplotlib not available")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--activeCsv", default="/content/drive/MyDrive/Coursework/CHEMENG 277/Final Project/runs_active.csv")
    ap.add_argument("--out", default="active_learning_heatmap.png")
    # Pass an empty list to parse_args() to prevent it from trying to parse kernel-specific arguments
    args = ap.parse_args([])

    active = pd.read_csv(args.activeCsv)
    active_base = active[(active["pipeHeight_mm"] == 8.0) & (active["D"] == 1.88e9)].copy()

    # Pivot table: placement x Qtot
    pivot = active_base.pivot_table(index="placement", columns="Qtot_uLmin", values="N", aggfunc="count", fill_value=0)

    # Reorder
    placement_order = ["T", "S", "SZ", "TS"]
    pivot = pivot.reindex(placement_order)

    fig, ax = plt.subplots(figsize=(7, 4), dpi=150)
    im = ax.imshow(pivot.values, cmap="Blues", aspect="auto")

    ax.set_xticks(np.arange(len(pivot.columns)))
    ax.set_yticks(np.arange(len(pivot.index)))
    ax.set_xticklabels([int(c) for c in pivot.columns])
    ax.set_yticklabels(pivot.index)

    ax.set_xlabel("Flow rate (μL/min)", fontsize=11, weight='bold')
    ax.set_ylabel("Placement", fontsize=11, weight='bold')
    ax.set_title("Selection of candidate points\n(20 new points, baseline geometry)", fontsize=12, weight='bold')

    # Annotate counts
    for i in range(len(pivot.index)):
        for j in range(len(pivot.columns)):
            val = pivot.values[i, j]
            if not np.isnan(val) and val != 0: # Only annotate non-NaN and non-zero values
                text = ax.text(j, i, int(val), ha="center", va="center", color="black", fontsize=10)

    plt.colorbar(im, ax=ax, label="Count")
    plt.tight_layout()
    plt.savefig(args.out)
    plt.close()
    print(f"Saved {args.out}")

if __name__ == "__main__":
    main()

from IPython.display import Image
Image('active_learning_heatmap.png')

import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score, mean_absolute_error

df = pd.read_csv("/content/drive/MyDrive/Coursework/CHEMENG 277/Final Project/dead_volume_with_preds_combined_dedup.csv")
feature_cols = ["pipeHeight_mm", "D", "placement", "N", "Qtot_uLmin"]

df_enc = df[feature_cols + ["deadFraction", "source"]].dropna().copy()
le = LabelEncoder()
df_enc["placement"] = le.fit_transform(df_enc["placement"])

df_orig = df_enc[df_enc["source"] == "orig"].copy()
df_act = df_enc[df_enc["source"] == "active"].copy()

X_train = df_orig[feature_cols].values
y_train = df_orig["deadFraction"].values
X_test = df_act[feature_cols].values
y_test = df_act["deadFraction"].values

print(f"Training on {len(X_train)} orig, testing on {len(X_test)} active")

gbm = GradientBoostingRegressor(n_estimators=200, max_depth=4, learning_rate=0.05, random_state=0)
gbm.fit(X_train, y_train)

# Test performance (honest)
pred_test = gbm.predict(X_test)
r2_test = r2_score(y_test, pred_test)
mae_test = mean_absolute_error(y_test, pred_test)
print(f"\nTest on 20 active points:")
print(f"  R² = {r2_test:.3f}")
print(f"  MAE = {mae_test:.4f}")

# Training performance (will be high due to overfitting)
pred_train = gbm.predict(X_train)
r2_train = r2_score(y_train, pred_train)
mae_train = mean_absolute_error(y_train, pred_train)
print(f"\nTraining on 103 orig points:")
print(f"  R² = {r2_train:.3f}")
print(f"  MAE = {mae_train:.4f}")

"""Random forest tuning"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Re-load the main dataframe and re-preprocess categorical features
df_full = pd.read_csv("/content/drive/MyDrive/Coursework/CHEMENG 277/Final Project/dead_volume_with_preds_combined_dedup.csv")
feature_cols = ["pipeHeight_mm", "D", "placement", "N", "Qtot_uLmin"]
df_processed = df_full[feature_cols + ["deadFraction", "source"]].dropna().copy()

le_plot = LabelEncoder()
df_processed["placement_encoded"] = le_plot.fit_transform(df_processed["placement"])

# Filter to get original and active data
df_orig_plot = df_processed[df_processed["source" ] == "orig"].copy()
df_act_plot = df_processed[df_processed["source"] == "active"].copy()

# --- Create DataFrames for plotting ---
plot_df_train = pd.DataFrame({
    'True Values': y_train,
    'Predicted Values': pred_train_rf,
    'Residuals': y_train - pred_train_rf,
    'Placement': le_plot.inverse_transform(df_orig_plot['placement_encoded']),
    'Dataset': 'Training'
})

plot_df_test = pd.DataFrame({
    'True Values': y_test,
    'Predicted Values': pred_test_rf,
    'Residuals': y_test - pred_test_rf,
    'Placement': le_plot.inverse_transform(df_act_plot['placement_encoded']),
    'Dataset': 'Test'
})

# Combine for unified plotting
plot_df = pd.concat([plot_df_train, plot_df_test])

# --- Plotting ---
fig, axes = plt.subplots(1, 2, figsize=(18, 7), dpi=150)
placement_cmap = {"T":"tab:blue", "S":"tab:orange", "SZ":"tab:green", "TS":"tab:red"}

# 1. Predicted vs. True Values
sns.scatterplot(x='True Values', y='Predicted Values', hue='Placement', data=plot_df, palette=placement_cmap, s=50, alpha=0.7, edgecolors='w', linewidth=0.5, ax=axes[0])
min_val, max_val = plot_df[['True Values', 'Predicted Values']].min().min(), plot_df[['True Values', 'Predicted Values']].max().max()
axes[0].plot([min_val, max_val], [min_val, max_val], '--r', label='Perfect Prediction', linewidth=1.5)
axes[0].set_title('Random Forest: Predicted vs. True Values', fontsize=16)
axes[0].set_xlabel('True dead volume fraction')
axes[0].set_ylabel('Predicted dead volume fraction')
axes[0].legend(title='Placement', bbox_to_anchor=(1.05, 1), loc='upper left')

# 2. Residuals
sns.scatterplot(x='Predicted Values', y='Residuals', hue='Placement', data=plot_df, palette=placement_cmap, s=50, alpha=0.7, edgecolors='w', linewidth=0.5, ax=axes[1])
axes[1].axhline(y=0, color='r', linestyle='--', linewidth=1.5)
axes[1].set_title('Random Forest: Residuals vs. Predicted Values', fontsize=16)
axes[1].set_xlabel('Predicted dead volume fraction')
axes[1].set_ylabel('Residuals (Pred - True)')
axes[1].legend(title='Placement', bbox_to_anchor=(1.05, 1), loc='upper left')

plt.tight_layout(rect=[0, 0, 0.85, 1])
plt.show()

"""Random forest model"""

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score, mean_absolute_error

# Load the dataset
df = pd.read_csv("/content/drive/MyDrive/Coursework/CHEMENG 277/Final Project/dead_volume_with_preds_combined_dedup.csv")
feature_cols = ["pipeHeight_mm", "D", "placement", "N", "Qtot_uLmin"]

# Preprocess categorical features
df_enc = df[feature_cols + ["deadFraction", "source"]].dropna().copy()
le = LabelEncoder()
df_enc["placement"] = le.fit_transform(df_enc["placement"])

# Split data into original (training) and active (testing)
df_orig = df_enc[df_enc["source"] == "orig"].copy()
df_act = df_enc[df_enc["source"] == "active"].copy()

X_train = df_orig[feature_cols].values
y_train = df_orig["deadFraction"].values
X_test = df_act[feature_cols].values
y_test = df_act["deadFraction"].values

print(f"Training Random Forest on {len(X_train)} orig, testing on {len(X_test)} active")

# Initialize and train a RandomForestRegressor with default parameters
rf_model = RandomForestRegressor(random_state=0)
rf_model.fit(X_train, y_train)

# Test performance
pred_test_rf = rf_model.predict(X_test)
r2_test_rf = r2_score(y_test, pred_test_rf)
mae_test_rf = mean_absolute_error(y_test, pred_test_rf)
print(f"\nTest performance with RandomForest (on {len(X_test)} active points):")
print(f"  R2 Score = {r2_test_rf:.3f}")
print(f"  MAE = {mae_test_rf:.4f}")

# Training performance
pred_train_rf = rf_model.predict(X_train)
r2_train_rf = r2_score(y_train, pred_train_rf)
mae_train_rf = mean_absolute_error(y_train, pred_train_rf)
print(f"\nTraining performance with RandomForest (on {len(X_train)} orig points):")
print(f"  R2 Score = {r2_train_rf:.3f}")
print(f"  MAE = {mae_train_rf:.4f}")

"""GBM model tuning"""

import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import r2_score, mean_absolute_error

# Load the dataset (using the path from your previous successful execution)
df = pd.read_csv("/content/drive/MyDrive/Coursework/CHEMENG 277/Final Project/dead_volume_with_preds_combined_dedup.csv")
feature_cols = ["pipeHeight_mm", "D", "placement", "N", "Qtot_uLmin"]

# Preprocess categorical features (as done previously)
df_enc = df[feature_cols + ["deadFraction", "source"]].dropna().copy()
le = LabelEncoder()
df_enc["placement"] = le.fit_transform(df_enc["placement"])

# Split data into original (training) and active (testing)
df_orig = df_enc[df_enc["source"] == "orig"].copy()
df_act = df_enc[df_enc["source"] == "active"].copy()

X_train = df_orig[feature_cols].values
y_train = df_orig["deadFraction"].values
X_test = df_act[feature_cols].values
y_test = df_act["deadFraction"].values

print(f"Training on {len(X_train)} orig, testing on {len(X_test)} active")

# Define the parameter grid to search with a wider range and more aggressive regularization
param_grid = {
    'n_estimators': [50, 100, 200, 300], # Keeping a wide range of estimators
    'max_depth': [1, 2, 3], # Smaller trees to reduce complexity
    'learning_rate': [0.005, 0.01, 0.05, 0.1], # Wider range for learning rate
    'subsample': [0.7, 0.8, 0.9, 1.0], # Fraction of samples to be used for fitting the individual base learners
    'min_samples_leaf': [5, 10, 15] # Larger minimum number of samples required to be at a leaf node for more regularization
}

# Initialize a GradientBoostingRegressor model
gbm = GradientBoostingRegressor(random_state=0)

# Initialize GridSearchCV
# We'll use 5-fold cross-validation (cv=5)
# 'neg_mean_absolute_error' is chosen as the scoring metric to optimize for lower MAE
grid_search = GridSearchCV(estimator=gbm, param_grid=param_grid,
                           cv=5, scoring='neg_mean_absolute_error', n_jobs=-1, verbose=1)

# Perform the grid search on the training data
grid_search.fit(X_train, y_train)

print(f"\nBest parameters found: {grid_search.best_params_}")

# Get the best model
best_gbm = grid_search.best_estimator_

# Evaluate the best model on the test set
pred_test_tuned = best_gbm.predict(X_test)
r2_test_tuned = r2_score(y_test, pred_test_tuned)
mae_test_tuned = mean_absolute_error(y_test, pred_test_tuned)
print(f"\nTest performance with tuned GBM (on {len(X_test)} active points):")
print(f"  R² = {r2_test_tuned:.3f}")
print(f"  MAE = {mae_test_tuned:.4f}")

# Evaluate the best model on the training set
pred_train_tuned = best_gbm.predict(X_train)
r2_train_tuned = r2_score(y_train, pred_train_tuned)
mae_train_tuned = mean_absolute_error(y_train, pred_train_tuned)
print(f"\nTraining performance with tuned GBM (on {len(X_train)} orig points):")
print(f"  R² = {r2_train_tuned:.3f}")
print(f"  MAE = {mae_train_tuned:.4f}")

"""Code for training of all three models"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import RidgeCV
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error

# 2. Define the feature_cols list
feature_cols = ["pipeHeight_mm", "D", "placement", "N", "Qtot_uLmin"]

# 3. Load the dataset
df_full = pd.read_csv("/content/drive/MyDrive/Coursework/CHEMENG 277/Final Project/dead_volume_with_preds_combined_dedup.csv")

# 4. Create a DataFrame df_processed and handle missing values
df_processed = df_full[feature_cols + ["deadFraction", "source"]].dropna().copy()

# 5. Initialize a LabelEncoder and fit-transform the "placement" column
# Note: This is specifically for GBM and RF which can handle integer encoded categories.
# For Ridge, OneHotEncoder will be used within its pipeline.
le_plot = LabelEncoder()
df_processed["placement_encoded"] = le_plot.fit_transform(df_processed["placement"])

# Prepare feature_cols for models that use integer encoding for 'placement'
feature_cols_encoded = ["pipeHeight_mm", "D", "placement_encoded", "N", "Qtot_uLmin"]

# 6. Filter df_processed to create df_orig and df_act
df_orig = df_processed[df_processed["source"] == "orig"].copy()
df_act = df_processed[df_processed["source"] == "active"].copy()

# 7. Define training and testing data for models that use integer encoding
X_train_encoded = df_orig[feature_cols_encoded].values
y_train = df_orig["deadFraction"].values
X_test_encoded = df_act[feature_cols_encoded].values
y_test = df_act["deadFraction"].values

print(f"Original training data points: {len(X_train_encoded)}")
print(f"Active testing data points: {len(X_test_encoded)}")

# 8. Define the make_ridge_pipeline function
def make_ridge_pipeline(features):
    cat_cols = ["placement"] # Use original 'placement' column for OneHotEncoding
    num_cols = [c for c in features if c not in cat_cols]

    preprocessor = ColumnTransformer(
        transformers=[
            ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
            ("num", StandardScaler(), num_cols),
        ],
        remainder="drop"
    )
    alphas = np.logspace(-6, 6, 61)
    return Pipeline(steps=[
        ("pre", preprocessor),
        ("ridge", RidgeCV(alphas=alphas, cv=5))
    ])

# Prepare X_train and X_test using original 'placement' column for Ridge
X_train_ridge = df_orig[feature_cols]
X_test_ridge = df_act[feature_cols]

# 9. Re-train Ridge Regression Model:
print("\n--- Re-training Ridge Regression Model ---")
ridge_model = make_ridge_pipeline(feature_cols)
ridge_model.fit(X_train_ridge, y_train)

pred_train_ridge = ridge_model.predict(X_train_ridge)
pred_test_ridge = ridge_model.predict(X_test_ridge)

r2_train_ridge = r2_score(y_train, pred_train_ridge)
mae_train_ridge = mean_absolute_error(y_train, pred_train_ridge)
r2_test_ridge = r2_score(y_test, pred_test_ridge)
mae_test_ridge = mean_absolute_error(y_test, pred_test_ridge)

print(f"Ridge Training R²: {r2_train_ridge:.3f}")
print(f"Ridge Training MAE: {mae_train_ridge:.4f}")
print(f"Ridge Test R²: {r2_test_ridge:.3f}")
print(f"Ridge Test MAE: {mae_test_ridge:.4f}")


# 10. Re-train Initial Gradient Boosting Machine (GBM) Model:
print("\n--- Re-training Initial Gradient Boosting Machine (GBM) Model ---")
gbm_model = GradientBoostingRegressor(n_estimators=200, max_depth=4, learning_rate=0.05, random_state=0)
gbm_model.fit(X_train_encoded, y_train)

pred_train_gbm = gbm_model.predict(X_train_encoded)
pred_test_gbm = gbm_model.predict(X_test_encoded)

r2_train_gbm = r2_score(y_train, pred_train_gbm)
mae_train_gbm = mean_absolute_error(y_train, pred_train_gbm)
r2_test_gbm = r2_score(y_test, pred_test_gbm)
mae_test_gbm = mean_absolute_error(y_test, pred_test_gbm)

print(f"GBM Training R²: {r2_train_gbm:.3f}")
print(f"GBM Training MAE: {mae_train_gbm:.4f}")
print(f"GBM Test R²: {r2_test_gbm:.3f}")
print(f"GBM Test MAE: {mae_test_gbm:.4f}")


# 11. Re-train Tuned Random Forest Model:
print("\n--- Re-training Tuned Random Forest Model ---")
# Parameters from previous best_rf = grid_search_rf.best_estimator_
rf_tuned_model = RandomForestRegressor(n_estimators=50, max_depth=10, min_samples_leaf=1, random_state=0)
rf_tuned_model.fit(X_train_encoded, y_train)

pred_train_rf_tuned = rf_tuned_model.predict(X_train_encoded)
pred_test_rf_tuned = rf_tuned_model.predict(X_test_encoded)

r2_train_rf_tuned = r2_score(y_train, pred_train_rf_tuned)
mae_train_rf_tuned = mean_absolute_error(y_train, pred_train_rf_tuned)
r2_test_rf_tuned = r2_score(y_test, pred_test_rf_tuned)
mae_test_rf_tuned = mean_absolute_error(y_test, pred_test_rf_tuned)

print(f"Tuned RF Training R²: {r2_train_rf_tuned:.3f}")
print(f"Tuned RF Training MAE: {mae_train_rf_tuned:.4f}")
print(f"Tuned RF Test R²: {r2_test_rf_tuned:.3f}")
print(f"Tuned RF Test MAE: {mae_test_rf_tuned:.4f}")

"""## Plotting for model comparison - combined data set (not included in final report)


"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import RidgeCV
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error

# 1. Load the combined dataset
csv_path = '/content/drive/MyDrive/Coursework/CHEMENG 277/Final Project/dead_volume_with_preds_combined_dedup.csv'
df_final = pd.read_csv(csv_path).dropna(subset=['pipeHeight_mm', 'D', 'placement', 'N', 'Qtot_uLmin', 'deadFraction']).copy()

feature_cols = ['pipeHeight_mm', 'D', 'placement', 'N', 'Qtot_uLmin']
target_col = 'deadFraction'
y_full = df_final[target_col].values

# 2. Encoding for tree-based models
le = LabelEncoder()
df_final['placement_encoded'] = le.fit_transform(df_final['placement'])
feature_cols_tree = ['pipeHeight_mm', 'D', 'placement_encoded', 'N', 'Qtot_uLmin']

# 3. Fit Ridge
cat_cols = ['placement']
num_cols = [c for c in feature_cols if c not in cat_cols]
preprocessor = ColumnTransformer(transformers=[('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols), ('num', StandardScaler(), num_cols)], remainder='drop')
ridge_final = Pipeline(steps=[('pre', preprocessor), ('ridge', RidgeCV(alphas=np.logspace(-6, 6, 61), cv=5))])
ridge_final.fit(df_final[feature_cols], y_full)
y_pred_ridge = ridge_final.predict(df_final[feature_cols])

# 4. Fit GBM
gbm_final = GradientBoostingRegressor(n_estimators=200, max_depth=4, learning_rate=0.05, random_state=0)
gbm_final.fit(df_final[feature_cols_tree], y_full)
y_pred_gbm = gbm_final.predict(df_final[feature_cols_tree])

# 5. Fit RF
rf_final = RandomForestRegressor(n_estimators=50, max_depth=10, min_samples_leaf=1, random_state=0)
rf_final.fit(df_final[feature_cols_tree], y_full)
y_pred_rf = rf_final.predict(df_final[feature_cols_tree])

# 6. Plotting
placement_cmap = {'T': 'tab:blue', 'S': 'tab:orange', 'SZ': 'tab:green', 'TS': 'tab:red'}
all_vals = np.concatenate([y_full, y_pred_ridge, y_pred_gbm, y_pred_rf])
limits = [all_vals.min() - 0.05, all_vals.max() + 0.05]

fig, axes = plt.subplots(1, 3, figsize=(18, 6), dpi=150)
models_data = [('Ridge Regression', y_pred_ridge), ('Gradient Boosting', y_pred_gbm), ('Random Forest', y_pred_rf)]

for i, (title, y_pred) in enumerate(models_data):
    ax = axes[i]
    sns.scatterplot(data=df_final, x=target_col, y=y_pred, hue='placement', palette=placement_cmap, s=50, alpha=0.7, ax=ax)
    ax.plot(limits, limits, '--r', lw=1.5)
    ax.set_title(title, fontsize=14)
    ax.set_xlabel('True Values'); ax.set_ylabel('Predicted Values')
    ax.set_xlim(limits); ax.set_ylim(limits)
    ax.text(0.05, 0.95, f"R² = {r2_score(y_full, y_pred):.3f}\nMAE = {mean_absolute_error(y_full, y_pred):.4f}", transform=ax.transAxes, verticalalignment='top', bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))
    ax.legend(title='Placement', loc='lower right')

plt.tight_layout()
plt.savefig('model_comparison_plot.png')
plt.show()

import pandas as pd

# Create a dictionary to store the metrics
metrics_data = {
    'Model': ['Ridge Regression', 'Ridge Regression',
              'Gradient Boosting Machine', 'Gradient Boosting Machine',
              'Tuned Random Forest', 'Tuned Random Forest'],
    'Dataset': ['Training', 'Test', 'Training', 'Test', 'Training', 'Test'],
    'R2 Score': [r2_train_ridge, r2_test_ridge,
                 r2_train_gbm, r2_test_gbm,
                 r2_train_rf_tuned, r2_test_rf_tuned],
    'MAE': [mae_train_ridge, mae_test_ridge,
            mae_train_gbm, mae_test_gbm,
            mae_train_rf_tuned, mae_test_rf_tuned]
}

# Create the DataFrame
df_metrics = pd.DataFrame(metrics_data)

# Display the metrics table
print("\n--- Model Performance Summary ---")
print(df_metrics.to_string(index=False, formatters={'R2 Score': '{:.3f}'.format, 'MAE': '{:.4f}'.format}))

"""## Models on Original Data - tested on 20 acive learning points


"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import RidgeCV
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error

# 1. Load the combined dataset
csv_path = '/content/drive/MyDrive/Coursework/CHEMENG 277/Final Project/dead_volume_with_preds_combined_dedup.csv'
df_combined = pd.read_csv(csv_path)

# 2. Filter for only the original 104-point dataset
df_orig_only = df_combined[df_combined['source'] == 'orig'].copy()

# 3. Define feature columns and target
feature_cols = ['pipeHeight_mm', 'D', 'placement', 'N', 'Qtot_uLmin']
target_col = 'deadFraction'

# Clean data
df_final = df_orig_only[feature_cols + [target_col]].dropna().copy()
y_full = df_final[target_col].values

# 4. Handle categorical encoding
le = LabelEncoder()
df_final['placement_encoded'] = le.fit_transform(df_final['placement'])
feature_cols_encoded = ['pipeHeight_mm', 'D', 'placement_encoded', 'N', 'Qtot_uLmin']

# 5. Ridge Regression Pipeline
def make_ridge_pipeline(features):
    cat_cols = ['placement']
    num_cols = [c for c in features if c not in cat_cols]
    preprocessor = ColumnTransformer(
        transformers=[
            ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols),
            ('num', StandardScaler(), num_cols),
        ],
        remainder='drop'
    )
    alphas = np.logspace(-6, 6, 61)
    return Pipeline(steps=[
        ('pre', preprocessor),
        ('ridge', RidgeCV(alphas=alphas, cv=5))
    ])

# Fit Ridge
ridge_final = make_ridge_pipeline(feature_cols)
ridge_final.fit(df_final[feature_cols], y_full)
y_pred_ridge = ridge_final.predict(df_final[feature_cols])

# 6. Fit GBM
gbm_final = GradientBoostingRegressor(n_estimators=200, max_depth=4, learning_rate=0.05, random_state=0)
gbm_final.fit(df_final[feature_cols_encoded], y_full)
y_pred_gbm = gbm_final.predict(df_final[feature_cols_encoded])

# 7. Fit Tuned RF
rf_final = RandomForestRegressor(n_estimators=50, max_depth=10, min_samples_leaf=1, random_state=0)
rf_final.fit(df_final[feature_cols_encoded], y_full)
y_pred_rf = rf_final.predict(df_final[feature_cols_encoded])

# 8. Calculate Metrics
results = []
for name, y_pred in [('Ridge', y_pred_ridge), ('GBM', y_pred_gbm), ('Tuned RF', y_pred_rf)]:
    results.append({
        'Model': name,
        'R2': r2_score(y_full, y_pred),
        'MAE': mean_absolute_error(y_full, y_pred)
    })

df_results = pd.DataFrame(results)
print("Final Model Performance on Original 104-point Dataset (n={}):".format(len(df_final)))
print(df_results.to_string(index=False))

"""### Plot for final model comparison

"""

import pandas as pd

# Data from previous executions stored in variables or hardcoded from standard output history
comparison_data = {
    'Model': ['Ridge Regression', 'Gradient Boosting', 'Random Forest'],
    'Original Dataset Only (n=98) R²': [0.568, 0.997, 0.984],
    'Original Dataset Only (n=98) MAE': [0.0326, 0.0024, 0.0044],
    'Full Combined Dataset (n=118) R²': [0.166, 0.994, 0.982],
    'Full Combined Dataset (n=118) MAE': [0.0551, 0.0034, 0.0052]
}

df_comp = pd.DataFrame(comparison_data)

print("--- Impact of Adding Active Learning Points on Training Fit ---")
display(df_comp.style.format({
    'Original Dataset Only (n=98) R²': '{:.3f}',
    'Original Dataset Only (n=98) MAE': '{:.4f}',
    'Full Combined Dataset (n=118) R²': '{:.3f}',
    'Full Combined Dataset (n=118) MAE': '{:.4f}'
}))

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.metrics import r2_score, mean_absolute_error

# 1. Define a consistent color map for the 'placement' categories
placement_cmap = {'T': 'tab:blue', 'S': 'tab:orange', 'SZ': 'tab:green', 'TS': 'tab:red'}

# Prepare data for plotting
plot_data = df_final.copy()
plot_data['Ridge_Pred'] = y_pred_ridge
plot_data['GBM_Pred'] = y_pred_gbm
plot_data['RF_Pred'] = y_pred_rf

# 2. Calculate global limits for uniform axis scaling
all_vals = np.concatenate([y_full, y_pred_ridge, y_pred_gbm, y_pred_rf])
min_val, max_val = all_vals.min(), all_vals.max()
pad = (max_val - min_val) * 0.05
limits = [min_val - pad, max_val + pad]

# 3. Create a figure with three subplots
fig, axes = plt.subplots(1, 3, figsize=(18, 6), dpi=150)
models = [
    ('Ridge Regression', 'Ridge_Pred'),
    ('Gradient Boosting', 'GBM_Pred'),
    ('Tuned Random Forest', 'RF_Pred')
]

for i, (title, pred_col) in enumerate(models):
    ax = axes[i]

    # 4. Scatter plot colored by 'placement'
    sns.scatterplot(
        data=plot_data, x='deadFraction', y=pred_col, hue='placement',
        palette=placement_cmap, s=60, alpha=0.7, edgecolors='w', ax=ax
    )

    # 5. Plot diagonal dashed line (y=x)
    ax.plot(limits, limits, 'r--', lw=2, label='Perfect Prediction')

    # 6. Calculate and annotate R2 and MAE
    r2 = r2_score(y_full, plot_data[pred_col])
    mae = mean_absolute_error(y_full, plot_data[pred_col])
    stats_text = f'$R^2$: {r2:.3f}\nMAE: {mae:.4f}'
    ax.text(0.05, 0.95, stats_text, transform=ax.transAxes, verticalalignment='top',
            bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

    # 7. Labels and titles
    ax.set_title(title, fontsize=15, fontweight='bold')
    ax.set_xlabel('True dead volume fraction', fontsize=12)
    ax.set_ylabel('Predicted dead volume fraction', fontsize=12)
    ax.set_xlim(limits)
    ax.set_ylim(limits)
    ax.grid(True, linestyle='--', alpha=0.6)

    if i == 0:
        ax.legend(title='Placement', loc='lower right')
    else:
        ax.get_legend().remove()

# 8. Save and display
plt.tight_layout()
plt.savefig('final_model_comparison.png')
plt.show()
print('Figure saved as final_model_comparison.png')
print(f'Note: Plotting results for the original dataset only (n={len(df_final)})')

import pandas as pd

# 1. Consolidate final metrics from the combined dataset (n=118)
# Note: Metrics were calculated in the previous step during retraining.
final_metrics_data = {
    'Model': ['Ridge Regression', 'Gradient Boosting Machine', 'Tuned Random Forest'],
    'Dataset': ['Full Combined', 'Full Combined', 'Full Combined'],
    'R2 Score': [r2_score(y_full, y_pred_ridge), r2_score(y_full, y_pred_gbm), r2_score(y_full, y_pred_rf)],
    'MAE': [mean_absolute_error(y_full, y_pred_ridge), mean_absolute_error(y_full, y_pred_gbm), mean_absolute_error(y_full, y_pred_rf)]
}

df_final_metrics = pd.DataFrame(final_metrics_data)

# 2. Display the summary table with formatting
print("--- Final Performance Summary (Combined Dataset) ---")
print(df_final_metrics.to_string(index=False, formatters={'R2 Score': '{:.3f}'.format, 'MAE': '{:.4f}'.format}))

